name = "portfolio-website"
main = "src/worker.js"
compatibility_date = "2026-04-24"
workers_dev = true

[assets]
directory = "."
binding = "ASSETS"

[[routes]]
pattern = "kayleescanlin.dev/*"
zone_name = "kayleescanlin.dev"

[[routes]]
pattern = "www.kayleescanlin.dev/*"
zone_name = "kayleescanlin.dev"
